all:
	@echo "Write this Makefile by your self."

sim:
	$(call git_commit, "sim RTL") # DO NOT REMOVE THIS LINE!!!
	@echo "Write this Makefile by your self."

commit: 

	$(call git_commit, $(MyMessage)) # DO NOT REMOVE THIS LINE!!!
	@echo $(MyMessage)
include ../Makefile
